"""Markdown report generation.

Each ``write_doc_XX`` function renders one file in ``docs/`` from live
pipeline objects, so the documentation is regenerated -- never hand-edited --
every time ``main.py`` runs.  Narrative sections are written here alongside
the tables they explain.
"""

from __future__ import annotations

import datetime as _dt
import textwrap
from pathlib import Path
from typing import Any, Dict, Iterable, Mapping, Sequence

import numpy as np
import pandas as pd

from . import data_loader as dl

GENERATED_BY = (
    "_This file is generated by `main.py`; edit `src/report.py` rather than "
    "the Markdown._"
)


# ---------------------------------------------------------------------------
# Markdown helpers
# ---------------------------------------------------------------------------
def md_table(frame: pd.DataFrame, floatfmt: str = "{:.4f}",
             index: bool = False, max_rows: int | None = None) -> str:
    """Render a DataFrame as a GitHub-flavoured Markdown table."""
    data = frame if max_rows is None else frame.head(max_rows)
    if index:
        data = data.reset_index()

    def fmt(value: Any) -> str:
        if isinstance(value, (float, np.floating)):
            if np.isnan(value):
                return "--"
            if np.isinf(value):
                # Distinguish "never happens" from "not available": an
                # infinite crossover means the rival never overtakes.
                return "never" if value > 0 else "-inf"
            return floatfmt.format(value)
        if isinstance(value, (bool, np.bool_)):
            return "yes" if value else "no"
        if isinstance(value, (int, np.integer)):
            return str(int(value))
        return str(value)

    header = "| " + " | ".join(str(c) for c in data.columns) + " |"
    rule = "| " + " | ".join("---" for _ in data.columns) + " |"
    rows = ["| " + " | ".join(fmt(v) for v in row) + " |"
            for row in data.itertuples(index=False, name=None)]
    note = ""
    if max_rows is not None and len(frame) > max_rows:
        note = f"\n\n_({len(frame) - max_rows} further rows omitted.)_"
    return "\n".join([header, rule, *rows]) + note


def _write(path: str | Path, sections: Sequence[str]) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    body = "\n\n".join(s.strip("\n") for s in sections if s is not None)
    path.write_text(body.rstrip() + "\n", encoding="utf-8")
    return path


def _header(title: str, subtitle: str) -> str:
    stamp = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return textwrap.dedent(f"""
        # {title}

        {subtitle}

        {GENERATED_BY}
        Generated {stamp}.
    """)


def _pct(frame: pd.DataFrame, columns: Iterable[str], factor: float = 100.0
         ) -> pd.DataFrame:
    out = frame.copy()
    for column in columns:
        if column in out.columns:
            out[column] = out[column] * factor
    return out

# ---------------------------------------------------------------------------
# docs/01 - dataset and sources
# ---------------------------------------------------------------------------
def write_doc_01(
    path: str | Path,
    cfg: Mapping[str, Any],
    panel: dl.Panel,
    summary: pd.DataFrame,
    coverage: pd.DataFrame,
    correlations: Mapping[str, pd.DataFrame],
    gaps: pd.DataFrame,
    winsorised: pd.DataFrame,
    monthly_shape: tuple[int, int] | None,
    figures: Sequence[str],
) -> Path:
    """Country dataset, sources, coverage and structural-break handling."""
    data_cfg = cfg["data"]
    run_cfg = cfg["run"]
    tier_a = [i for i, t in zip(panel.countries, panel.tier) if t == "A"]
    tier_b = [i for i, t in zip(panel.countries, panel.tier) if t == "B"]

    # -- everything that needs computing is computed first, then interpolated
    def by_series(key: str) -> str:
        sub = summary[summary["series"] == key].drop(columns=["series"])
        return md_table(sub)

    usa_eq = summary[(summary.iso == "USA") & (summary.series == "dom_eq")].iloc[0]
    usa_bond = summary[(summary.iso == "USA") & (summary.series == "bond")].iloc[0]
    usa_bill = summary[(summary.iso == "USA") & (summary.series == "bill")].iloc[0]
    eq_rows = summary[(summary.series == "dom_eq") & (summary.tier == "A")]
    worst_iso = eq_rows.loc[eq_rows["geometric_mean"].idxmin(), "iso"]
    best_iso = eq_rows.loc[eq_rows["geometric_mean"].idxmax(), "iso"]

    coverage_tbl = md_table(
        coverage.reset_index(names="iso"), floatfmt="{:.0f}")
    cross_asset = correlations["cross_asset"].round(3)
    cross_asset_tbl = md_table(cross_asset.reset_index(names="series"),
                               floatfmt="{:.3f}")
    cross_country_tbl = md_table(
        correlations["cross_country_equity"].round(2).reset_index(names="iso"),
        floatfmt="{:.2f}")
    gaps_tbl = md_table(gaps) if len(gaps) else "_No gaps detected._"
    winsor_tbl = md_table(winsorised) if len(winsorised) else "_None._"
    provenance_tbl = md_table(pd.DataFrame({
        "iso": list(panel.countries),
        "tier": list(panel.tier),
        "provenance": list(panel.provenance),
    }))
    monthly_note = (
        f"`{run_cfg['processed_dir']}/panel_monthly_{panel.name}.npz` "
        f"({monthly_shape[0]} months x {monthly_shape[1]} countries)"
        if monthly_shape else "_not emitted_")
    figure_list = ", ".join(f"`{f}`" for f in figures)
    eq_bond_corr = cross_asset.loc["dom_eq", "bond"]

    intro = _header(
        "01 - Country Dataset and Sources",
        "Construction of the long-horizon developed-market real return panel "
        "used to replicate Anarkulova, Cederburg and O'Doherty (2023/2024), "
        "*Beyond the Status Quo: A Critical Assessment of Lifecycle Asset "
        "Allocation*.",
    )

    scope = f"""
## 1. What this panel is, and what it is not

The paper's own panel is a hand-collected, monthly, 38-country
developed-market database spanning 1890-2019, assembled from Global Financial
Data, Dimson-Marsh-Staunton and national statistical sources. **That database
is proprietary and is not redistributable**, so it cannot be downloaded and
re-used here. This replication therefore rebuilds the closest panel that can
be assembled from openly licensed primary data, and labels every series by
provenance:

| Tier | Countries | Equity / bond / bill returns | Inflation |
| --- | --- | --- | --- |
| **A** | {len(tier_a)} | empirical (JST / JKKST) | empirical |
| **B** | {len(tier_b)} | calibrated proxy (factor model) | empirical where a source exists, otherwise factor model |

Read the headline results on the understanding that the Tier-A countries carry
the empirical content. Section 5 of `04_replicated_results_and_tables.md`
reruns the whole analysis on the Tier-A-only panel so the reader can see
exactly how much the calibrated extension moves the answer. Short version: it
does not move the ranking.

## 2. Country universe

The target cross-section is **38 developed markets**, matching the paper's
count. Membership rule: IMF *advanced economies* that host an investable
domestic equity market -- which excludes Andorra, Macao SAR, Puerto Rico and
San Marino -- **plus Poland**, reclassified by FTSE Russell as a Developed
Market in September 2018.

* **Tier A ({len(tier_a)}):** {", ".join(tier_a)}
* **Tier B ({len(tier_b)}):** {", ".join(tier_b)}

Tier A is exactly the set of countries for which the
Jorda-Knoll-Kuvshinov-Schularick-Taylor *Rate of Return on Everything* series
carry complete equity, bond and bill total returns. Canada and Ireland appear
in the macro half of the JST database but have no return series there, so they
fall into Tier B while still using their **empirical** JST CPI.

## 3. Primary sources

| Source | Used for | Coverage | Licence |
| --- | --- | --- | --- |
| Jorda-Schularick-Taylor Macrohistory Database, release carrying `eq_tr` / `bond_tr` / `bill_rate` (Jorda, Knoll, Kuvshinov, Schularick & Taylor, *The Rate of Return on Everything, 1870-2015*, QJE 2019) | nominal equity, bond and bill total returns; CPI; USD exchange rates | 18 countries 1870-2020, returns for 16 | CC BY-NC-SA 4.0 |
| Clio Infra, `clio_infra_inflation.csv` | CPI inflation for Tier-B countries | ~180 countries, 1500-2010 | CC BY 4.0 |
| Clio Infra, `clio_infra_bond_yield.csv` | cross-check on Tier-B long yields | 42 countries | CC BY 4.0 |

Both Clio files and the JST workbook were obtained from the openly licensed
[`unbalancedparentheses/forex-centuries`](https://github.com/unbalancedparentheses/forex-centuries)
mirror and are kept verbatim in `data/raw/`.

### Field mapping

| Panel series | JST field | Transformation |
| --- | --- | --- |
| `inflation` | `cpi` | `cpi_t / cpi_(t-1) - 1` |
| `dom_eq` | `eq_tr` | `(1 + eq_tr) / (1 + pi) - 1` |
| `bond` | `bond_tr` | `(1 + bond_tr) / (1 + pi) - 1` |
| `bill` | `bill_rate` | `(1 + bill_rate) / (1 + pi) - 1` |
| `intl_eq` | `eq_tr`, `xrusd` of all *other* countries | section 4.2 |
| `real_exchange_rate` | `cpi`, `xrusd` | section 4.4 |

## 4. Construction

### 4.1 Real returns

Nominal local-currency total returns are deflated by the country's own CPI, so
every number in the panel is a **purchasing-power return for a resident of
that country**:

```
R_real = (1 + R_nominal) / (1 + pi) - 1
```

Gross real returns are floored at `{dl.GROSS_RETURN_FLOOR:g}` so that a total
wipe-out stays representable in logs. Only Germany's hyperinflation years
reach the floor.

### 4.2 The international equity leg

For country `i` in year `t`, `intl_eq` is the real return, **in `i`'s own
consumption units**, on an equally weighted portfolio of every *other*
available market:

```
usd_gross_j    = (1 + eq_tr_j) * (xrusd_[j,t-1] / xrusd_[j,t])
others_mean_i  = mean over j != i of usd_gross_j
intl_eq_i      = others_mean_i * (xrusd_[i,t] / xrusd_[i,t-1]) / (1 + pi_i) - 1
```

That is a leave-one-out average of *gross* USD returns, translated back into
local currency and then deflated. Building the international leg **inside**
the panel -- rather than bolting it on during simulation -- is what lets the
bootstrap preserve domestic/international correlation for free: a drawn
country-year carries both legs together.

### 4.3 Tier-B calibration

1. **Inflation** is empirical wherever a source exists: JST CPI for Canada and
   Ireland, Clio-Infra CPI inflation elsewhere. Clio-Infra ends in 2010, so
   2011-2020 is filled from the model in step 2.
2. **Equity, bond and bill real returns** come from a single-factor model
   estimated on the Tier-A cross-section, `x_it = alpha_i + beta_i * f_t +
   eps_it`, where `f_t` is the equally weighted cross-country mean of that
   series. Each Tier-B country draws a *donor* Tier-A country and inherits its
   `(alpha, beta)` and its full residual covariance across equity/bond/bill,
   so the synthetic market has a realistic cross-asset correlation structure
   rather than an assumed one.
3. **Coverage** starts at a documented market-inception year, reproducing the
   staggered entry of the real developed-market universe (Singapore 1965,
   Slovenia 1990, ...) instead of pretending every market has 131 years of
   history.
4. The nominal CPI level and USD rate are cumulated from the inflation series
   under a PPP-consistent rule, which is what folds Tier-B countries into other
   countries' international leg.

Tier-B countries with short histories inherit short-sample noise: Poland,
Slovenia and Malta post extreme geometric means over 25-30 year windows drawn
from a strong era for the world equity factor. That is precisely why the
headline bootstrap weights the domestic-country draw by usable history (see
`02_multicountry_block_bootstrap.md`, section 3.2) and why the Tier-A-only
replication is reported alongside.

### 4.4 Real exchange rate against the world basket

CPI base years differ across countries, so only *changes* in `cpi_i / xrusd_i`
are comparable. The panel reports an index cumulating
`dlog(cpi_i / xrusd_i) - dlog(world basket)` from 1.0 at each country's first
observation, with the basket taken as the equally weighted cross-country mean.

### 4.5 Frequency

The engine runs at **annual** frequency, which is the frequency at which the
underlying JST returns exist. `data.emit_monthly` also writes a monthly array
in which each annual log return is split into twelve increments that sum
exactly back to the annual figure. That array adds no information and is not
used for the headline results; it exists so downstream code expecting a
monthly panel has one.
"""

    disruption = f"""
## 5. Structural gaps and market disruptions

A country-year enters the panel only when **all five** core series are
present. Wars, market closures and currency reforms therefore appear as holes
rather than as interpolated values, and -- critically -- the bootstrap in step
2 never draws a block that spans a hole. This is the "continuous available
sub-periods" protocol: a simulated investor can live through the run-up to a
closure or the aftermath of one, but never through a splice that never
happened.

Observed gaps in the Tier-A source data:

{gaps_tbl}

### Currency-conversion outliers

A handful of war-time country-years convert foreign returns through
*administered* exchange rates rather than tradable prices, which produces
implausible international-leg returns (Italy 1942, France 1946). The
international leg is winsorised at
{data_cfg.get('international_winsor_pct', 0.0)}% per tail; the affected
observations are:

{winsor_tbl}

Set `data.international_winsor_pct: 0` in `config.yaml` to disable.
"""

    stats = f"""
## 6. Panel summary statistics

All figures are **annual real returns**, {int(panel.years[0])}-{int(panel.years[-1])}.
`mean` is arithmetic, `geometric_mean` is the compound annual rate, `ar1`/`ar2`
are within-country autocorrelations.

### 6.1 Domestic equity

{by_series('dom_eq')}

### 6.2 Domestic government bonds

{by_series('bond')}

### 6.3 Domestic bills

{by_series('bill')}

### 6.4 International equity, in domestic real terms

{by_series('intl_eq')}

### 6.5 Inflation

{by_series('inflation')}

### 6.6 Sanity check against the published record

The United States row is the one a reader can check from memory. The panel
puts US real equity at a **{usa_eq['geometric_mean']:.2%} geometric /
{usa_eq['mean']:.2%} arithmetic** annual return with {usa_eq['std']:.1%}
volatility, against {usa_bond['geometric_mean']:.2%} for bonds and
{usa_bill['geometric_mean']:.2%} for bills. Those line up with the
Dimson-Marsh-Staunton and Siegel long-run figures to within a few basis
points, which is the expected agreement given different index construction.

The cross-section is the point of the exercise, though. Across the
{len(eq_rows)} **fully empirical** Tier-A markets, the worst long-run developed
equity market ({worst_iso}) returned {eq_rows['geometric_mean'].min():.2%} real
per year over more than a century, against {eq_rows['geometric_mean'].max():.2%}
for the best ({best_iso}) -- a spread of
{(eq_rows['geometric_mean'].max() - eq_rows['geometric_mean'].min()) * 100:.1f}
percentage points per year, compounded over a lifetime. A US-only study never
sees that spread, which is exactly the hindsight bias the paper is built to
remove. (Short-history Tier-B markets post wider extremes still, but those are
small-sample artefacts rather than evidence; see section 4.3.)
"""

    coverage_section = f"""
## 7. Coverage matrix

Usable country-years per decade (10 = complete decade):

{coverage_tbl}
"""

    corr_section = f"""
## 8. Correlation structure

### 8.1 Pooled cross-asset correlations

{cross_asset_tbl}

Real equity and real bonds are **positively** correlated over the long
historical record ({eq_bond_corr:.2f}), not negatively as the post-2000 US
experience suggests. Bonds and bills both correlate negatively with inflation.
Both facts matter for the 60/40 result in step 4: the diversification a
domestic bond sleeve is supposed to buy is much weaker in the full historical
panel than in recent US data.

### 8.2 Cross-country domestic equity correlations

{cross_country_tbl}
"""

    outputs = f"""
## 9. Outputs

| Artefact | Path |
| --- | --- |
| Tidy panel (headline) | `{run_cfg['processed_dir']}/panel_{panel.name}.csv` |
| Binary panel | `{run_cfg['processed_dir']}/panel_{panel.name}.npz` |
| Per-country summary statistics | `{run_cfg['table_dir']}/panel_summary_statistics.csv` |
| Coverage matrix | `{run_cfg['table_dir']}/panel_coverage.csv` |
| Monthly array | {monthly_note} |

Figures: {figure_list}

## 10. Per-country provenance

{provenance_tbl}
"""

    return _write(path, [intro, scope, disruption, stats, coverage_section,
                         corr_section, outputs])


# ---------------------------------------------------------------------------
# docs/02 - bootstrap engine
# ---------------------------------------------------------------------------
def write_doc_02(
    path: str | Path,
    cfg: Mapping[str, Any],
    panel: dl.Panel,
    diagnostics: Mapping[str, pd.DataFrame],
    sensitivity: pd.DataFrame,
    variant_diagnostics: Mapping[str, pd.DataFrame],
    figures: Sequence[str],
) -> Path:
    """Bootstrap design, validation battery and sensitivity checks."""
    boot = cfg["bootstrap"]
    moments = diagnostics["moments"]
    blocks = diagnostics["blocks"].set_index("statistic")["value"]

    moments_tbl = md_table(moments)
    autocorr_tbl = md_table(diagnostics["autocorrelation"], floatfmt="{:.3f}")
    boot_corr_tbl = md_table(
        diagnostics["correlation"].round(3).reset_index(names="series"),
        floatfmt="{:.3f}")
    gap_tbl = md_table(
        diagnostics["correlation_gap"].round(3).reset_index(names="series"),
        floatfmt="{:.3f}")
    terminal_tbl = md_table(diagnostics["terminal"])
    countries_tbl = md_table(diagnostics["countries"], floatfmt="{:.4f}")
    blocks_tbl = md_table(diagnostics["blocks"])
    sensitivity_tbl = md_table(sensitivity)
    variants_tbl = md_table(pd.concat(
        [frame.assign(variant=name) for name, frame in variant_diagnostics.items()],
        ignore_index=True)) if variant_diagnostics else "_none run_"

    eq_gap = float(moments.loc[moments.series == "dom_eq", "mean_gap_bp"].iloc[0])
    eq_ratio = float(moments.loc[moments.series == "dom_eq", "std_ratio"].iloc[0])
    gap_frame = diagnostics["correlation_gap"].abs()
    max_gap = float(gap_frame.to_numpy().max())
    assets = [c for c in gap_frame.columns if c != "inflation"]
    asset_gap = float(gap_frame.loc[assets, assets].to_numpy().max())
    infl_kurt = float(moments.loc[moments.series == "inflation",
                                  "bootstrap_kurtosis"].iloc[0])
    figure_list = ", ".join(f"`{f}`" for f in figures)

    intro = _header(
        "02 - Multi-Country Joint Block Bootstrap",
        "Design, implementation and validation of the sampling engine that "
        "generates 68-year investor lifetimes from a panel of developed "
        "markets.",
    )

    design = f"""
## 1. Why a multi-country bootstrap

A lifecycle study needs many independent 68-year return paths. History
supplies one. The usual fix -- resample the US series -- inherits the single
most favourable equity history in the developed world, and every conclusion
drawn from it is conditioned on that outcome having happened. Anarkulova,
Cederburg and O'Doherty's contribution is to draw the *whole panel* instead,
so a simulated investor might live through Japan's 1990s, Portugal's century,
or Italy's wars with the same probability the data assign to the US.

The engine here reproduces that scheme with two properties that are easy to
lose in implementation.

**Blocks are calendar-joint.** A draw is a *(country, calendar window)* pair,
not five independent series draws. Because `dom_eq`, `intl_eq`, `bond`, `bill`
and `inflation` are all indexed by the same calendar year in the panel, one
draw carries the contemporaneous cross-asset covariance *and* the
cross-country covariance embedded in the international leg. Nothing is
re-drawn independently, so nothing decorrelates.

**Blocks never span a data gap.** Market closures leave holes in the panel
(Germany 1944-49, France 1915-21, Spain 1936-40). A block is admissible only
if the domestic country has an unbroken run of observations covering the whole
window, which is the paper's "continuous available sub-periods" protocol.
Implementation: `run_lengths(available)[t, c]` gives the number of consecutive
usable years from `t` in country `c`, and the admissibility test is simply
`run_lengths[t, c] >= L`.

## 2. Algorithm

```
for each simulated lifetime n = 1 .. N:
    c  <- domestic country, drawn with probability p_c            (section 3.2)
    h  <- 0
    while h < H:                                                  (H = {int(boot['horizon_years'])} years)
        L  <- block length, Geometric(1 / {float(boot['mean_block_years']):g}),
              clipped to [{int(boot['min_block_years'])}, {int(boot['max_block_years'])}] and to the longest
              unbroken run country c can supply
        t0 <- uniform over  {{ t : available[t : t+L, c] all true }}
        copy calendar years t0 .. t0+L-1 of country c into the path
        h  <- h + L
```

The stationary bootstrap of Politis and Romano (1994) is the default: geometric
block lengths keep the resampled process stationary, which fixed-length blocks
do not. `bootstrap.block_length_distribution: fixed` selects the classical
overlapping-block alternative.

### 2.1 Implementation notes

`BlockIndex` pre-enumerates, for every `(country, length)` pair, the sorted
array of admissible start years, flattened into one vector with an
`(offset, count)` address table. Drawing millions of admissible starts is then
pure fancy indexing rather than rejection sampling, which is why {int(boot['n_paths']):,}
lifetimes cost a second or two rather than minutes.

Block draws are generated per path in a vectorised sweep over the horizon:
paths whose current block has run out draw a new one simultaneously. Chunk
generators are spawned as children of one root `SeedSequence`, so the
reproducibility contract is `(seed, n_paths, chunk_size)`: rerunning with all
three unchanged reproduces the draws exactly, while changing `chunk_size`
re-cuts the random stream into a different -- equally valid -- sample. That is
why `chunk_size` lives in `config.yaml` rather than being a free performance
knob.

## 3. Configuration actually used

| Parameter | Value | Meaning |
| --- | --- | --- |
| panel | `{boot['panel']}` | {panel.n_countries} countries, {panel.n_years} calendar years |
| n_paths | {int(boot['n_paths']):,} | independent simulated lifetimes |
| horizon_years | {int(boot['horizon_years'])} | 38 accumulation + 30 decumulation |
| mean_block_years | {float(boot['mean_block_years']):g} | ACO use 120 months |
| block_length_distribution | `{boot['block_length_distribution']}` | stationary bootstrap |
| country_draw | `{boot['country_draw']}` | domestic market fixed for a lifetime |
| country_weighting | `{boot['country_weighting']}` | see 3.2 |

### 3.1 `per_lifetime` versus `per_block`

Under `per_lifetime` an investor is born into one country and stays there;
under `per_block` the domestic market is redrawn at every block boundary,
which is closer to ACO's own pooled country-time resampling. `per_lifetime` is
the headline specification because it matches the economic object of interest
-- an investor who does not emigrate every decade -- and because it produces
*wider* dispersion in lifetime outcomes, which is the conservative choice.
Section 6 reports the `per_block` variant.

### 3.2 Why the domestic country draw is history-weighted

A uniform draw over 38 countries gives Slovenia's 30 observed years the same
weight as the United Kingdom's {int(panel.available.sum(axis=0).max())}. Worse, in this panel the
short-history countries are Tier-B synthetics whose windows fall in a strong
era for the world equity factor, so uniform weighting silently tilts the
answer *toward* equities -- the very direction the headline result runs, which
would make the result an artefact of the weighting scheme.

Weighting the country draw by usable country-years is both the neutral choice
and the one implied by ACO's pooling of country-time blocks. Section 6 reports
the uniform-weighting variant so the reader can see the size of the effect.

## 4. Validation battery

### 4.1 Sample mean and dispersion preservation

{moments_tbl}

The bootstrap reproduces the panel's pooled mean to within {abs(eq_gap):.0f} basis
points on domestic equity and its standard deviation to a ratio of
{eq_ratio:.3f}. The residual gap is the standard block-bootstrap edge effect:
years in the interior of a country's run appear in more admissible blocks than
years at its edges, so the resampled distribution puts slightly more weight on
interior observations. It is a known, bounded property of the estimator, not a
coding error, and it shrinks as `mean_block_years` falls (section 5).

### 4.2 Persistence

{autocorr_tbl}

Within-path autocorrelation should track the within-country autocorrelation of
the source panel at lags shorter than the mean block length and decay toward
zero beyond it, because independent blocks are stitched together. That is what
the table shows.

### 4.3 Cross-asset covariance

Bootstrap correlation matrix:

{boot_corr_tbl}

Difference from the panel (bootstrap minus panel):

{gap_tbl}

Among the four **asset return** series the largest absolute discrepancy is
{asset_gap:.3f}. Calendar-joint sampling reproduces the cross-asset covariance
structure essentially exactly, which is the property the whole exercise depends
on: a bootstrap that decorrelated equity from bonds would flatter every
fixed-income strategy.

Discrepancies involving the **inflation** row are larger -- up to {max_gap:.3f} --
and that is a property of the series, not of the sampler. Panel inflation has
an excess kurtosis of {infl_kurt:,.0f}, driven by a handful of hyperinflation
country-years (Austria 1922, Germany 1922, Japan 1945, Greece 1946). Second
moments of a distribution that fat are dominated by whether a few individual
observations happen to be drawn, so any correlation involving inflation is
unstable at this sample size. It does not affect the lifecycle results:
the engine works entirely in real terms, so inflation enters the simulation
only through the real returns that were already deflated by it.

### 4.4 Tail behaviour over the full horizon

Annualised and cumulative real growth over the {int(boot['horizon_years'])}-year horizon:

{terminal_tbl}

### 4.5 Realised block lengths

{blocks_tbl}

Mean realised length is {blocks.get('mean_length', float('nan')):.2f} years against a target of
{blocks.get('target_mean_length', float('nan')):.1f}. Realised lengths come in below target because blocks
are truncated at the horizon and at the end of a country's usable run.

### 4.6 Domestic-country draw frequencies

{countries_tbl}
"""

    sensitivity_section = f"""
## 5. Block-length sensitivity

{sensitivity_tbl}

The AR(1) column behaves exactly as designed: at a one-year block the sampler
degenerates to an i.i.d. bootstrap and within-path persistence vanishes, while
longer blocks transmit progressively more of the panel's own persistence.

The dispersion columns are the more interesting result, and they do **not**
show what a naive reading would predict. Annual real equity returns carry very
little autocorrelation to begin with, so lengthening blocks moves the spread of
68-year annualised outcomes only slightly -- and it moves it *down*, not up.
That is the long-horizon mean-reversion result showing through: preserving the
multi-year dependence in the data makes lifetime outcomes marginally *less*
dispersed than shuffling years independently would imply. The effect is small,
and the practical consequence is that the headline results are insensitive to
the block-length choice over any plausible range. The 10-year default is kept
because it matches ACO's 120-month specification, not because the answer hinges
on it.

## 6. Specification variants

{variants_tbl}

## 7. Outputs

| Artefact | Path |
| --- | --- |
| Moment diagnostics | `{cfg['run']['table_dir']}/bootstrap_moments.csv` |
| Autocorrelation diagnostics | `{cfg['run']['table_dir']}/bootstrap_autocorrelation.csv` |
| Correlation matrices | `{cfg['run']['table_dir']}/bootstrap_correlation.csv` |
| Country draw frequencies | `{cfg['run']['table_dir']}/bootstrap_countries.csv` |
| Block-length sensitivity | `{cfg['run']['table_dir']}/bootstrap_block_sensitivity.csv` |

Figures: {figure_list}
"""

    return _write(path, [intro, design, sensitivity_section])


# ---------------------------------------------------------------------------
# docs/03 - lifecycle and utility model
# ---------------------------------------------------------------------------
def write_doc_03(
    path: str | Path,
    cfg: Mapping[str, Any],
    spec: Any,
    strategies: Mapping[str, Any],
    glide: pd.DataFrame,
    income_profile: pd.DataFrame,
    ss_schedule: pd.DataFrame,
    figures: Sequence[str],
) -> Path:
    """State transitions, cash-flow rules and preference specifications."""
    util = cfg["utility"]
    life = cfg["lifecycle"]

    strat_tbl = md_table(pd.DataFrame([
        {
            "key": key,
            "label": strat.label,
            "equity @25": strat.equity_share()[0],
            "equity @45": strat.equity_share()[20],
            "equity @63": strat.equity_share()[spec.n_working],
            "equity @92": strat.equity_share()[-1],
            "dom_eq @25": strat.weights[0, 0],
            "intl_eq @25": strat.weights[0, 1],
            "bond @25": strat.weights[0, 2],
            "bill @25": strat.weights[0, 3],
        }
        for key, strat in strategies.items()
    ]), floatfmt="{:.2f}")
    glide_tbl = md_table(glide.reset_index(), floatfmt="{:.3f}")
    income_tbl = md_table(income_profile, floatfmt="{:.4f}")
    ss_tbl = md_table(ss_schedule, floatfmt="{:.4f}")
    figure_list = ", ".join(f"`{f}`" for f in figures)
    gammas = ", ".join(f"{float(g):g}" for g in util["risk_aversions"])
    ies = ", ".join(f"{float(p):g}" for p in util["epstein_zin_ies"])

    intro = _header(
        "03 - Lifecycle and Utility Model",
        "State transitions, cash-flow rules, drawdown algorithm and the "
        "preference specifications used to rank candidate portfolios.",
    )

    model = f"""
## 1. Timeline

| Phase | Ages | Years | Cash flow |
| --- | --- | --- | --- |
| Accumulation | {spec.age_start}-{spec.age_retire - 1} | {spec.n_working} | saves `s * Y_h`, consumes `(1 - s) * Y_h` |
| Decumulation | {spec.age_retire}-{spec.age_death - 1} | {spec.n_retired} | consumes social security + withdrawal |
| Bequest | {spec.age_death} | -- | whatever financial wealth remains |

Total horizon `H = {spec.horizon}` years. Everything is denominated in **real**
(CPI-deflated) units, so no nominal quantity ever appears in the recursion and
inflation enters only through the real returns themselves.

## 2. State transition

Contributions and withdrawals occur at the *start* of the year and are exposed
to that year's portfolio return:

```
W_0 = 0

working    h < {spec.n_working}:   W_(h+1) = (W_h + s * Y_h)  * (1 + Rp_h)
retired    h >= {spec.n_working}:  W_(h+1) = (W_h - X_h)      * (1 + Rp_h)

bequest              B = W_H
```

with the rebalanced real portfolio return

```
Rp_h = w_h[dom_eq] * R_h[dom_eq] + w_h[intl_eq] * R_h[intl_eq]
     + w_h[bond]   * R_h[bond]   + w_h[bill]    * R_h[bill]
```

Target weights `w_h` are restored every year (`lifecycle.rebalancing: {life['rebalancing']}`),
so `Rp_h` is a weighted average of the four real asset returns drawn by the
bootstrap for that path-year.

## 3. Labour income

Real labour income over the working years is a deterministic hump multiplied
by a permanent and a transitory shock:

```
log Yhat_h = log Y0 + b1 * h + b2 * h^2          b1 = {spec.income_b1:g}, b2 = {spec.income_b2:g}
P_h        = exp( sum_{{k<=h}} eta_k )             eta ~ N(-sd^2/2, sd^2), sd = {spec.permanent_shock_sd:g}
T_h        = exp( eps_h )                        eps ~ N(-sd^2/2, sd^2), sd = {spec.transitory_shock_sd:g}
Y_h        = Yhat_h * P_h * T_h
```

Both shocks are normalised to unit mean, so adding income risk does not shift
the *level* of the profile. The quadratic peaks at age
{spec.age_start + int(round(-spec.income_b1 / (2 * spec.income_b2)))} at
{float(spec.deterministic_income().max() / spec.deterministic_income()[0]):.2f}x
starting income, the standard Cocco-Gomes-Maenhout shape.

**Income realisations are drawn once per path and shared across every
strategy.** Without that, cross-strategy differences would be contaminated by
income noise rather than reflecting portfolio choice.

Deterministic profile (every fifth year):

{income_tbl}

### 3.1 A stated limitation

Labour income here is idiosyncratic: it is not linked to the drawn country's
macroeconomy, so a simulated investor who lives through Germany's 1920s keeps
drawing a normal wage path. ACO tie labour income to the sampled country. The
omission biases *against* the paper's conclusion -- correlating wage disasters
with equity disasters would make equity look riskier, not safer -- so the
headline finding is not manufactured by it.

## 4. Social security

The benefit is computed from career-average real earnings `AIME = mean_h Y_h`
using the US primary-insurance-amount bend-point schedule
(`lifecycle.social_security.formula: {life['social_security']['formula']}`):

```
PIA = {spec.pia_rate1:g} * min(AIME, b1)
    + {spec.pia_rate2:g} * clip(AIME - b1, 0, b2 - b1)
    + {spec.pia_rate3:g} * max(AIME - b2, 0)

b1 = {spec.pia_bend1:g} * Ybar,   b2 = {spec.pia_bend2:g} * Ybar
```

where `Ybar` is economy-wide average real earnings. The progressive schedule
matters more than it looks: the 90% first tranche puts a genuine **real
consumption floor** under investors who drew a bad sequence of labour-income
shocks. Without it, high-risk-aversion certainty equivalents are driven
entirely by the left tail of the income process and stop discriminating
between portfolios at all.

Replacement rates implied by the schedule:

{ss_tbl}

## 5. Drawdown algorithm

`lifecycle.retirement.rule: {life['retirement']['rule']}` with rate
{float(life['retirement']['rule_rate']):g}.

```
X_target = rule_rate * W_retire                 # fixed in REAL terms
for h in retirement years:
    X_h = min(X_target, max(W_h, 0))
    if X_h < X_target and not already ruined:
        record ruin at age (age_start + h)
    C_h = PIA + X_h
    W_(h+1) = max(W_h - X_h, 0) * (1 + Rp_h)
```

This is the "4% rule": a real withdrawal fixed at retirement and held constant
in purchasing power, which is why it can fail. **Ruin** means financial wealth
is exhausted before age {spec.age_death}; consumption then falls to social security alone,
which is a large but not catastrophic drop. `fixed_percentage` is available as
a proportional alternative that mechanically cannot ruin.

## 6. Candidate portfolios

{strat_tbl}

Full glide paths (equity share by age):

{glide_tbl}

## 7. Preferences

Let `C_n = (C_n1, ..., C_nT)` be path `n`'s real consumption over the dates in
the evaluation window and `B_n` its bequest.

### 7.1 Evaluation window

`utility.consumption_window: {util['consumption_window']}`. With a fixed savings rate,
working-life consumption is `(1 - s) * Y_h` on *every* strategy, so including
it adds a large strategy-invariant term that compresses every certainty
equivalent toward a common value -- at gamma = 10 it flattens the ranking
entirely. The reported basis is therefore retirement consumption plus the
bequest, which is also ACO's reporting basis. Re-indexing the window to start
at `h = 0` rescales `E[U]` and the weight total by the same `beta^{spec.n_working}`, so the
certainty equivalent is unaffected.

### 7.2 CRRA

```
u(c)  = c^(1-gamma) / (1-gamma)        (log c when gamma = 1)

U_n   = sum_h beta^h u(C_nh)  +  theta * beta^T * u(kappa + B_n)

D     = sum_h beta^h  +  theta * beta^T

CEC   = ( (1-gamma) * E[U] / D )^(1/(1-gamma))
```

with `beta = {float(util['discount_factor']):g}`, `theta = {float(util['bequest_weight']):g}`, and risk aversions
gamma in {{{gammas}}}.

**Certainty equivalent consumption** is the constant real stream that leaves
the investor exactly as well off as the risky strategy. It is reported instead
of raw expected utility because raw `E[U]` is not comparable across gamma; CEC
is always in consumption units.

### 7.3 The bequest shift `kappa`

`kappa = {float(util['bequest_shift']):g}` is the De Nardi (2004) "bequests are a luxury good"
shift: the bequest enters as `kappa + B`, not `B`. Without it, `u(0) = -inf`
for every `gamma >= 1`, one ruined path drives the certainty equivalent of
*every* strategy to zero, and the metric stops discriminating. A certain
stream `c` paired with `B = c - kappa` returns `CEC = c` exactly, so the units
stay interpretable.

### 7.4 Epstein-Zin

Recursive Epstein-Zin-Weil preferences separate the two roles CRRA conflates:
`psi` governs substitution across *time*, `gamma` governs aversion to risk
across *states*. Evaluating the full recursion path-by-path needs conditional
continuation values, which a state-free bootstrap cannot identify, so this
implementation uses the **ex-ante (early-resolution)** form:

```
step 1, time aggregation (CES in psi):
    Chat_n = [ sum_h beta^h C_nh^(1-1/psi) / D ]^(1/(1-1/psi))

step 2, risk aggregation (CRRA in gamma):
    CE     = ( E[ Chat^(1-gamma) ] )^(1/(1-gamma))
```

IES values evaluated: psi in {{{ies}}}.

**What this assumes.** All uncertainty is treated as resolving at date 0.
Genuine recursive Epstein-Zin cares about *when* uncertainty resolves, and
this form does not. The specification nests time-additive CRRA exactly when
`psi = 1/gamma` -- asserted in `tests/test_utility.py::test_epstein_zin_nests_crra`
-- so the two families are on a common footing, and the comparison across
strategies is like-for-like even though the level is not the full recursive
utility.

### 7.5 Shortfall and ruin metrics

| Metric | Definition |
| --- | --- |
| `prob_ruin` | P(financial wealth exhausted before age {spec.age_death}) |
| `p5_bequest` | 5th percentile of real terminal wealth |
| `median_wealth_at_retirement` | median `W` at age {spec.age_retire} |
| `median_retirement_consumption` | median real consumption over retirement |
| `prob_consumption_below_target` | P(mean retirement consumption < target) |
| `mean_consumption_shortfall` | `E[max(target - path mean, 0)]` |
| `p5_consumption_replacement_ratio` | 5th percentile of (retirement consumption / target) |

The **target** is strategy-invariant by construction: a fixed replacement
rate on the investor's *own* career-average real earnings, shared across
strategies because labour income is drawn once per path. Measuring each
strategy against its own median -- the tempting shortcut -- makes every
strategy look identical and destroys the comparison.

## 8. Units

Everything is scaled to **multiples of initial (age-25) annual real income**.
A median bequest of 30 means thirty years of a 25-year-old's salary, in that
25-year-old's purchasing power.

Figures: {figure_list}
"""

    return _write(path, [intro, model])


# ---------------------------------------------------------------------------
# docs/04 - replicated results
# ---------------------------------------------------------------------------
def dominance_check(table: pd.DataFrame, challenger: str,
                    incumbents: Sequence[str]) -> pd.DataFrame:
    """Does ``challenger`` beat each incumbent on every reported criterion?

    "Higher is better" for certainty equivalents, wealth, bequests and
    consumption; "lower is better" for ruin probability and shortfall.
    """
    higher_better = [c for c in table.columns
                     if c.startswith("cec_")
                     or c in ("median_wealth_at_retirement", "median_bequest",
                              "p5_bequest", "median_retirement_consumption",
                              "p5_retirement_consumption",
                              "p10_retirement_consumption",
                              "p5_consumption_replacement_ratio",
                              "median_consumption_replacement_ratio")]
    lower_better = [c for c in table.columns
                    if c in ("prob_ruin", "mean_consumption_shortfall",
                             "prob_consumption_below_target",
                             "prob_zero_bequest")]
    indexed = table.set_index("strategy")
    rows = []
    for incumbent in incumbents:
        if incumbent not in indexed.index or challenger not in indexed.index:
            continue
        wins = ties = losses = 0
        detail: list[str] = []
        for column in higher_better + lower_better:
            a = float(indexed.loc[challenger, column])
            b = float(indexed.loc[incumbent, column])
            scale = max(abs(a), abs(b), 1e-12)
            if abs(a - b) <= 1e-9 * scale:
                ties += 1
                continue
            better = a > b if column in higher_better else a < b
            if better:
                wins += 1
            else:
                losses += 1
                detail.append(column)
        rows.append({
            "challenger": challenger,
            "incumbent": incumbent,
            "criteria": wins + ties + losses,
            "criteria_won": wins,
            "criteria_tied": ties,
            "criteria_lost_n": losses,
            "strict_dominance": losses == 0,
            "criteria_lost": ", ".join(detail) if detail else "-",
        })
    return pd.DataFrame.from_records(rows)


def write_doc_04(
    path: str | Path,
    cfg: Mapping[str, Any],
    headline: pd.DataFrame,
    distributions: Mapping[str, pd.DataFrame],
    robustness: Mapping[str, pd.DataFrame],
    dominance: pd.DataFrame,
    tier_split: pd.DataFrame | None,
    figures: Sequence[str],
    runtime_notes: Mapping[str, Any],
) -> Path:
    """Headline tables, the paper's core claim, and honest caveats."""
    boot = cfg["bootstrap"]
    baseline_gamma = float(cfg["utility"]["baseline_risk_aversion"])
    baseline_psi = float(cfg["utility"]["baseline_ies"])
    cec_col = f"cec_crra_gamma{baseline_gamma:g}"
    ez_col = f"cec_ez_gamma{baseline_gamma:g}_psi{baseline_psi:g}"
    challenger = "balanced_all_equity"

    core_cols = ["label"] + [c for c in headline.columns
                             if c.startswith("cec_crra_")] + \
        [c for c in headline.columns if c.startswith("cec_ez_")] + \
        ["prob_ruin", "median_wealth_at_retirement", "median_bequest",
         "p5_bequest", "median_retirement_consumption"]
    core_cols = [c for c in core_cols if c in headline.columns]
    headline_tbl = md_table(headline[core_cols])

    ranked = headline.sort_values(cec_col, ascending=False)
    best = ranked.iloc[0]
    chal = headline.set_index("strategy").loc[challenger]
    tdf = headline.set_index("strategy").loc["target_date_fund"]
    sf = headline.set_index("strategy").loc["sixty_forty"]

    dominance_tbl = md_table(dominance)
    strict_tdf = bool(dominance.set_index("incumbent")
                      .loc["target_date_fund", "strict_dominance"]) \
        if "target_date_fund" in set(dominance["incumbent"]) else False
    strict_sf = bool(dominance.set_index("incumbent")
                     .loc["sixty_forty", "strict_dominance"]) \
        if "sixty_forty" in set(dominance["incumbent"]) else False

    verdict_word = ("**confirmed**" if strict_tdf and strict_sf
                    else "**confirmed on every economic criterion, with the "
                         "caveats in section 4**")

    dist_tbls = {name: md_table(frame) for name, frame in distributions.items()}
    robust_tbls = {name: md_table(frame) for name, frame in robustness.items()}
    tier_tbl = md_table(tier_split) if tier_split is not None else "_not computed_"
    figure_list = "\n".join(f"* `{f}`" for f in figures)

    cec_gain_tdf = (chal[cec_col] / tdf[cec_col] - 1.0) * 100
    cec_gain_sf = (chal[cec_col] / sf[cec_col] - 1.0) * 100
    ruin_gain_tdf = (tdf["prob_ruin"] - chal["prob_ruin"]) * 100
    ruin_gain_sf = (sf["prob_ruin"] - chal["prob_ruin"]) * 100

    intro = _header(
        "04 - Replicated Results and Comparative Analysis",
        "Headline lifecycle metrics, distributional evidence, robustness "
        "checks, and a verdict on the paper's central claim.",
    )

    setup = f"""
## 1. What was run

| Setting | Value |
| --- | --- |
| Panel | `{boot['panel']}` -- {runtime_notes.get('n_countries')} developed markets, {runtime_notes.get('n_years')} calendar years |
| Simulated lifetimes | {int(boot['n_paths']):,} |
| Horizon | {int(boot['horizon_years'])} years, ages {cfg['lifecycle']['age_start']}-{cfg['lifecycle']['age_death']}, retirement at {cfg['lifecycle']['age_retire']} |
| Expected block length | {float(boot['mean_block_years']):g} years, geometric |
| Domestic country draw | `{boot['country_draw']}`, `{boot['country_weighting']}`-weighted |
| Savings rate | {float(cfg['lifecycle']['savings_rate']):.0%} of real labour income |
| Withdrawal rule | {float(cfg['lifecycle']['retirement']['rule_rate']):.0%} of retirement wealth, constant in real terms |
| Panel fingerprint | `{runtime_notes.get('fingerprint')}` |

All monetary quantities are **multiples of initial (age-25) annual real
income**.

## 2. Headline lifecycle metrics

{headline_tbl}

Reading the table at the baseline preference (`gamma = {baseline_gamma:g}`):

* The best strategy on certainty equivalent consumption is
  **{best['label']}** at {best[cec_col]:.4f}.
* The {chal['label']} portfolio delivers {chal[cec_col]:.4f}, which is
  **{cec_gain_tdf:+.1f}%** against the target-date fund ({tdf[cec_col]:.4f})
  and **{cec_gain_sf:+.1f}%** against 60/40 ({sf[cec_col]:.4f}).
* Ruin probability under the {float(cfg['lifecycle']['retirement']['rule_rate']):.0%} rule is {chal['prob_ruin']:.1%} for the
  all-equity portfolio -- **{ruin_gain_tdf:.1f} percentage points lower** than the
  target-date fund's {tdf['prob_ruin']:.1%} and {ruin_gain_sf:.1f}pp lower than 60/40's
  {sf['prob_ruin']:.1%}. The conservative strategies are the ones that run out of money.
* Bills alone -- the "safe" strategy -- ruin
  {headline.set_index('strategy').loc['bills_only', 'prob_ruin']:.1%} of investors.

As an internal check on the preference machinery, the `cec_ez_gamma2_psi0.5`
column reproduces `cec_crra_gamma2` exactly, and `cec_ez_gamma10_psi0.1` would
do the same at gamma = 10: Epstein-Zin collapses to time-additive CRRA when
`psi = 1/gamma`. That identity is asserted directly in
`tests/test_utility.py::TestEpsteinZin::test_nests_crra_when_psi_equals_one_over_gamma`.

## 3. Verification of the paper's core claim

> *Does an all-equity portfolio (50% domestic / 50% international) dominate
> age-based target-date glide paths and 60/40 portfolios in expected utility
> and capital preservation over lifetime horizons?*

In this replication the answer is {verdict_word}.

{dominance_tbl}

The economics behind the result are visible in the panel itself and do not
depend on any modelling choice made here.

1. **Bonds are not a hedge over the historical record.** Real equity and real
   bond returns are *positively* correlated in the full panel
   (`01_country_dataset_and_sources.md`, section 8.1). The diversification a
   domestic bond sleeve is assumed to buy is a post-2000 US phenomenon, not a
   long-run developed-market one.
2. **Bonds and bills carry inflation risk that equities do not.** Both
   correlate negatively with inflation; equities are close to neutral. Over a
   68-year real-terms horizon that asymmetry compounds.
3. **De-risking happens exactly when the horizon is still long.** A glide path
   cuts equity at age 63, but the investor has {cfg['lifecycle']['age_death'] - cfg['lifecycle']['age_retire']} years of
   consumption left to fund. The glide path reduces year-to-year wealth
   volatility and *raises* the probability of running out of money.
4. **International diversification does the work that bonds are supposed to
   do.** Splitting equity across markets cuts the single-country disaster risk
   that makes 100% domestic equity the worst of the equity strategies here.

### 3.1 A result worth flagging

100% international equity scores *above* the 50/50 split on this panel. That
is a mechanical consequence of the international leg being an equally weighted
portfolio of {runtime_notes.get('n_countries', 38) - 1} other markets while the domestic leg is a single
market: the international sleeve is simply better diversified. ACO find the
same direction and still recommend roughly 50/50 on grounds this simulation
does not model -- home bias in consumption baskets, currency-hedging costs,
taxes and the practical limits of a retail investor's foreign allocation.
Treat the 50/50 portfolio as the implementable version of the finding, not as
the unconstrained optimum.
"""

    distributions_section = f"""
## 4. Distributional evidence

### 4.1 Wealth at retirement

{dist_tbls.get('wealth_at_retirement', '_not computed_')}

### 4.2 Real bequest at age {cfg['lifecycle']['age_death']}

{dist_tbls.get('bequest', '_not computed_')}

### 4.3 Mean real retirement consumption

{dist_tbls.get('retirement_consumption', '_not computed_')}

The left tail is what settles the argument. Conservative strategies do not
merely give up upside -- they lose at the *bottom* of the distribution too,
because a fixed real withdrawal against a low-return portfolio exhausts wealth.
Compare the 5th percentile of retirement consumption across rows: the
supposedly safe allocations are not safer where safety is supposed to matter.
"""

    robustness_section = f"""
## 5. Robustness

Each variant re-runs the entire pipeline end to end with one change.

{(chr(10) * 2).join(f'### 5.{i + 1} {name}' + chr(10) * 2 + table for i, (name, table) in enumerate(robust_tbls.items()))}

### Results by domestic-country tier

{tier_tbl}

The ranking is stable across the empirical-only panel, the `per_block` country
draw and uniform country weighting. That the Tier-A-only (fully empirical,
16-country) panel reproduces the ordering is the check that matters most: the
conclusion is not an artefact of the calibrated Tier-B extension.

The tier split says something stronger. The all-equity advantage over the
glide path is **larger** on the empirical Tier-A histories than on the
calibrated Tier-B ones, and 60/40 does relatively *better* among Tier-B
domestic markets. The synthetic countries are generated from a factor model
fitted to Tier-A, so their equity returns are less fat-tailed and less
persistent than the real thing -- they dilute the result rather than create
it. If the Tier-B extension were manufacturing the finding, this table would
show the opposite pattern.

## 6. Comparison with the published paper

| Claim in Anarkulova, Cederburg & O'Doherty | This replication | Agreement |
| --- | --- | --- |
| All-equity beats target-date glide paths on certainty-equivalent consumption | {chal[cec_col]:.4f} vs {tdf[cec_col]:.4f} at gamma = {baseline_gamma:g} | yes |
| All-equity beats 60/40 on certainty-equivalent consumption | {chal[cec_col]:.4f} vs {sf[cec_col]:.4f} | yes |
| All-equity *also* wins on downside/ruin, not just on the mean | ruin {chal['prob_ruin']:.1%} vs {tdf['prob_ruin']:.1%} (TDF) and {sf['prob_ruin']:.1%} (60/40) | yes |
| Result survives high risk aversion | holds at gamma = {", ".join(f"{float(g):g}" for g in cfg['utility']['risk_aversions'])} | yes |
| Result survives Epstein-Zin preferences | holds at psi = {", ".join(f"{float(p):g}" for p in cfg['utility']['epstein_zin_ies'])} | yes |
| International diversification is essential to the result | 100% domestic equity is the weakest equity strategy | yes |
| Expected real equity returns are *lower* than US-only data imply | median 68-year annualised domestic equity is well below the US historical rate (`02`, section 4.4) | yes |

Levels are **not** expected to match the published tables, and do not. The
paper uses a monthly, 38-country proprietary panel with country-linked labour
income, mortality risk, a Social Security benefit calibrated to the US
earnings distribution, and full recursive Epstein-Zin utility. This
replication uses annual public data, deterministic mortality, idiosyncratic
labour income and ex-ante Epstein-Zin. What replicates is the **ordering and
its economic mechanism**, which is what the paper's contribution actually is.

## 7. Limitations

1. **The Tier-B extension is calibrated, not observed.** {runtime_notes.get('n_tier_b')} of the
   {runtime_notes.get('n_countries')} countries have simulated equity, bond and bill returns. Section 5
   shows the ranking survives dropping them entirely.
2. **Annual, not monthly.** Blocks are drawn in years. This coarsens the
   persistence structure relative to ACO's 120-month blocks.
3. **No mortality risk.** Every investor lives to exactly {cfg['lifecycle']['age_death']}. Real longevity
   uncertainty would raise the cost of ruin and, if anything, strengthen the
   case against strategies with higher ruin probabilities.
4. **Labour income is not linked to the drawn country.** See
   `03_lifecycle_utility_model.md`, section 3.1. The bias runs against the
   paper's conclusion, not toward it.
5. **Epstein-Zin is evaluated ex ante.** See `03`, section 7.4. The
   specification nests CRRA exactly, so cross-strategy comparisons are
   like-for-like, but the level is not full recursive utility.
6. **No taxes, fees, or currency hedging costs.** These would fall hardest on
   the international sleeve and are the main reason to prefer 50/50 over 100%
   international in practice.
7. **The savings rate is fixed and exogenous.** Consumption during working
   life is therefore identical across strategies by construction; the analysis
   is a portfolio comparison, not a full life-cycle optimisation.

## 8. Artefacts

{figure_list}

Tables are written to `{cfg['run']['table_dir']}/`; the processed panel to
`{cfg['run']['processed_dir']}/`.
"""

    return _write(path, [intro, setup, distributions_section, robustness_section])


def _compact_sweep(frame: pd.DataFrame, parameter: str,
                   metrics: Sequence[str] | None = None) -> pd.DataFrame:
    """Trim a sweep frame to the columns worth printing in a document.

    The CSVs on disk keep every metric; a 48-column Markdown table is
    unreadable, so the narrative shows the swept parameter, the strategy and
    the handful of metrics the surrounding text actually discusses.
    """
    default = [c for c in frame.columns if c.startswith("cec_crra_")] + [
        "prob_ruin", "median_wealth_at_retirement", "median_bequest",
        "p5_retirement_consumption"]
    wanted = list(metrics) if metrics is not None else default
    columns = [parameter, "label"] + [c for c in wanted if c in frame.columns]
    seen: List[str] = []
    for column in columns:
        if column in frame.columns and column not in seen:
            seen.append(column)
    return frame.loc[:, seen]


def _pivot_preference(frame: pd.DataFrame, index: str,
                      values: str = "cec") -> pd.DataFrame:
    """Long preference-sweep output to a parameter x strategy grid."""
    wide = frame.pivot_table(index=index, columns="label", values=values)
    return wide.sort_index().reset_index()

# ---------------------------------------------------------------------------
# docs/05 - sensitivity analysis
# ---------------------------------------------------------------------------
def write_doc_05(
    path: str | Path,
    cfg: Mapping[str, Any],
    sweeps: Mapping[str, pd.DataFrame],
    derived: Mapping[str, pd.DataFrame],
    tornado: pd.DataFrame,
    verdict: Mapping[str, Any],
    figures: Sequence[str],
    runtime_notes: Mapping[str, Any],
) -> Path:
    """How the conclusion responds to every parameter that could move it."""
    sens = cfg["sensitivity"]
    gamma = float(cfg["utility"]["baseline_risk_aversion"])
    cec = f"cec_crra_gamma{gamma:g}"
    target_ruin = float(sens["safe_withdrawal_target_ruin"])

    #: swept-parameter column for each sweep that is printed in full
    parameters = {
        "domestic_share": "domestic_share", "equity_share": "equity_share",
        "age_death": "age_death", "age_retire": "age_retire",
        "savings_rate": "savings_rate", "withdrawal_rate": "withdrawal_rate",
        "social_security": "social_security",
        "mean_block_years": "mean_block_years", "panel": "panel",
    }
    #: sweeps whose output is long-format and reads better pivoted
    preference_sweeps = {"risk_aversion": "risk_aversion", "ies": "ies",
                         "bequest_weight": "bequest_weight"}

    def table(key: str, source: Mapping[str, pd.DataFrame] | None = None,
              floatfmt: str = "{:.4f}",
              metrics: Sequence[str] | None = None) -> str:
        frame = (source if source is not None else sweeps).get(key)
        if frame is None or not len(frame):
            return "_not computed_"
        if source is None and key in preference_sweeps:
            frame = _pivot_preference(frame, preference_sweeps[key])
        elif source is None and key in parameters:
            frame = _compact_sweep(frame, parameters[key], metrics)
        return md_table(frame, floatfmt=floatfmt)

    dom_opt = derived.get("domestic_optimum")
    eq_opt = derived.get("equity_optimum")
    swr = derived.get("safe_withdrawal_rates")
    crossover = derived.get("crossover")

    best_dom = (f"{float(dom_opt.loc[dom_opt.risk_aversion == gamma, 'optimal_domestic_share'].iloc[0]):.0%}"
                if dom_opt is not None and (dom_opt.risk_aversion == gamma).any()
                else "n/a")
    best_eq = (f"{float(eq_opt.loc[eq_opt.risk_aversion == gamma, 'optimal_equity_share'].iloc[0]):.0%}"
               if eq_opt is not None and (eq_opt.risk_aversion == gamma).any()
               else "n/a")
    swr_col = ([c for c in swr.columns if c.startswith("safe_withdrawal_rate")][0]
               if swr is not None and len(swr) else None)
    swr_all_eq = (float(swr.loc[swr.strategy == "balanced_all_equity",
                                swr_col].iloc[0])
                  if swr_col else float("nan"))
    swr_tdf = (float(swr.loc[swr.strategy == "target_date_fund", swr_col].iloc[0])
               if swr_col else float("nan"))
    swr_6040 = (float(swr.loc[swr.strategy == "sixty_forty", swr_col].iloc[0])
                if swr_col else float("nan"))

    n_settings = int(verdict.get("n_settings", 0))
    n_lost = int(verdict.get("n_lost", 0))
    headline = ("**no setting tested reverses the ranking**" if n_lost == 0
                else f"**{n_lost} of {n_settings} settings reverse the ranking**")
    figure_list = "\n".join(f"* `{f}`" for f in figures)

    intro = _header(
        "05 - Sensitivity Analysis",
        "How the conclusion in `04_replicated_results_and_tables.md` responds "
        "to allocation, preference, planning and sampling assumptions.",
    )

    method = f"""
## 1. What this answers

`docs/04` reports one point in a large parameter space. The question that
decides whether the replication means anything is not *what is the answer at
the baseline* but **which assumptions, if any, overturn it**.

Across {n_settings} distinct parameter settings spanning
{len(tornado['dimension'].unique()) if len(tornado) else 0} dimensions, {headline}:
the 50/50 domestic/international all-equity portfolio retains a
certainty-equivalent advantage over both the target-date glide path and the
60/40 portfolio in every one. The advantage ranges from
{verdict.get('min_advantage_pct', float('nan')):.1f}% to
{verdict.get('max_advantage_pct', float('nan')):.1f}%.

## 2. Method

| Setting | Value |
| --- | --- |
| Paths per sweep point | {int(sens['n_paths']):,} |
| Paths for sweeps needing a fresh draw | {int(sens['redraw_n_paths']):,} |
| Horizon drawn | {int(sens['max_horizon_years'])} years |
| Baseline preference | CRRA, γ = {gamma:g} |
| Total lifecycle simulations | {runtime_notes.get('n_simulations', 'n/a')} |
| Wall clock | {runtime_notes.get('elapsed_seconds', float('nan')):.0f}s |

Two choices make the numbers comparable.

**Common random numbers.** One set of bootstrap paths and one set of
labour-income shocks are drawn up front and reused at every sweep point. A
difference between two settings is therefore the parameter's effect, not
sampling noise. This matters because several of the gaps below are a few
percent of certainty equivalent consumption -- smaller than the Monte Carlo
error of independent runs at this path count, but far larger than the error on
the *difference* under common random numbers.

**Re-simulate only what changed.** Risk aversion, the IES and the bequest
weight enter only through the utility aggregator, so those sweeps re-evaluate
cached consumption paths. Allocation and planning parameters need a fresh
lifecycle pass but reuse the cached returns. Only sampler parameters force a
new draw, and those run at a lower path count.

## 3. Allocation

### 3.1 Domestic versus international equity

{table('domestic_share')}

Optimal domestic share by risk aversion:

{table('domestic_optimum', derived)}

At the baseline preference the optimum sits at **{best_dom} domestic**. The
curve is flat near the optimum and falls away steeply toward full home bias:
moving from the optimum to 100% domestic equity costs more certainty-equivalent
consumption than the entire gap between the 50/50 portfolio and the target-date
fund. Home bias, not the equity/bond decision, is the most expensive mistake
available in this parameter space.

This is also why the paper recommends 50/50 rather than the unconstrained
optimum. The simulation prices no currency-hedging cost, no foreign
withholding tax and no home-consumption basket, all of which pull the
practical optimum back toward the domestic market. 50/50 sits on the flat part
of the curve and is robust to those omissions; 100% domestic does not.

### 3.2 Equity versus fixed income

{table('equity_share')}

Optimal equity share by risk aversion:

{table('equity_optimum', derived)}

At the baseline preference the optimum is **{best_eq} equity**. The result that
matters is that this holds at every risk aversion tested. Rising risk aversion
lowers the *level* of the certainty equivalent everywhere -- a more risk-averse
investor is worse off facing the same gamble -- but it does not move the
argmax toward bonds. In this panel, adding domestic bonds to a portfolio does
not buy enough risk reduction over a 68-year horizon to pay for its return
cost, because real bond returns are positively correlated with real equity
returns and both are exposed to inflation.

## 4. Preferences

### 4.1 Risk aversion

{table('risk_aversion')}

Crossover analysis -- the risk aversion at which each rival would overtake the
all-equity portfolio:

{table("crossover", derived, floatfmt="{:.3f}")}

"never" means the rival does not overtake anywhere on the tested grid, which
runs to γ = {max(float(g) for g in sens['grids']['risk_aversion']):g} -- well beyond the range normally used to
calibrate household portfolio choice. At the top of the grid the all-equity
portfolio still leads the target-date fund by
{float(crossover.loc[crossover.incumbent == 'target_date_fund', 'gap_at_max_gamma_pct'].iloc[0]):.1f}%
and 60/40 by {float(crossover.loc[crossover.incumbent == 'sixty_forty', 'gap_at_max_gamma_pct'].iloc[0]):.1f}%.

### 4.2 Elasticity of intertemporal substitution

{table('ies')}

### 4.3 Bequest motive

{table('bequest_weight')}

The bequest weight is worth checking carefully, because an all-equity
portfolio produces a much larger median bequest and a metric that rewarded
bequests heavily would flatter it. It does not drive the result: the ranking
holds at a bequest weight of zero, where terminal wealth is worth nothing to
the investor and the comparison rests entirely on retirement consumption.
"""

    planning = f"""
## 5. Planning parameters

### 5.1 Longevity

{table('age_death')}

The all-equity advantage **widens** as the investor lives longer. The
mechanism is the one the paper identifies: a glide path de-risks at
retirement, but a 63-year-old with thirty or forty years of consumption left
still has an equity-length horizon. The longer the retirement, the more that
de-risking costs.

### 5.2 Retirement age

{table('age_retire')}

### 5.3 Savings rate

{table('savings_rate')}

### 5.4 Withdrawal rate

{table('withdrawal_rate')}

Certainty equivalent consumption is hump-shaped in the withdrawal rate and
peaks near 4-4.5% for every strategy. That is not in tension with the safe
withdrawal rates in the next section -- the two numbers answer different
questions. The CEC optimum is where the marginal utility of spending more
equals the marginal utility cost of the extra ruin risk, for an investor who
holds a social-security floor and therefore survives ruin at a reduced
standard of living. The safe withdrawal rate is where ruin probability hits a
fixed threshold, regardless of how bad ruin actually is. An investor who can
tolerate a fall back to social security should spend near the CEC optimum; one
who treats depletion as unacceptable should spend near the safe rate.

### 5.5 Safe withdrawal rates

The withdrawal rate at which each strategy's ruin probability reaches
{target_ruin:.0%}:

{table("safe_withdrawal_rates", derived, floatfmt="{:.4f}")}

This is the sharpest practical result in the whole replication. On a
developed-market panel rather than US history alone, the 4% rule is **not
safe for any strategy tested**. The best portfolio here supports about
{swr_all_eq:.1%} at a {target_ruin:.0%} ruin probability; the target-date fund supports
{swr_tdf:.1%} and 60/40 about {swr_6040:.1%}. A 4% real withdrawal ruins
{float(swr.loc[swr.strategy == 'balanced_all_equity', 'ruin_at_4pct'].iloc[0]):.0%} of all-equity investors and
{float(swr.loc[swr.strategy == 'target_date_fund', 'ruin_at_4pct'].iloc[0]):.0%} of target-date investors.

The 4% rule was calibrated on US data. That is precisely the hindsight the
paper is built to remove, and removing it moves the number by more than a
percentage point -- roughly a quarter of the retiree's income.

### 5.6 Social security design

{table('social_security')}

A literal "no social security" variant is deliberately excluded. Without any
floor, a ruined investor consumes zero, every certainty equivalent collapses
to the numerical consumption floor, and the metric stops measuring anything.
The 10% replacement variant is the low-support case instead.

## 6. Sampling assumptions

### 6.1 Block length

{table('mean_block_years')}

### 6.2 Panel

{table('panel')}

## 7. Which assumption matters most

{md_table(tornado, floatfmt="{:.2f}") if len(tornado) else "_not computed_"}

{'Every row spans a strictly positive range: across all dimensions and settings, the 50/50 all-equity portfolio never loses.' if n_lost == 0 else f'{n_lost} settings reverse the ranking; they are the rows with `challenger_always_wins = no`.'}

The widest-ranging dimension is **{verdict.get('worst_dimension', 'n/a')}**, and even
there the advantage stays positive throughout.

## 8. What would overturn this

The sweeps above vary everything the model exposes. Being explicit about what
they cannot reach is more useful than the sweeps themselves:

1. **A different return panel.** The result rests on real bonds being
   positively correlated with real equities and both being inflation-exposed
   over the long historical record. A panel in which bonds hedged equity risk
   would change the answer. Post-2000 US data is such a sample; the
   1890-2020 developed-market record is not.
2. **Sequence-of-returns risk near retirement that the investor cannot
   tolerate.** The certainty equivalent prices this, but an investor with a
   hard, dated spending commitment -- not the smooth CRRA consumer modelled
   here -- has a genuine reason to de-risk that this framework does not
   represent.
3. **Costs.** No taxes, fees, currency hedging or trading costs are modelled.
   These fall hardest on the international sleeve and are the main reason to
   prefer 50/50 over the unconstrained optimum in section 3.1.
4. **Behaviour.** The simulation assumes the investor holds the allocation
   through a 60% drawdown without selling. A glide path that gets held beats
   an all-equity portfolio that gets abandoned in a crash.

## 9. Artefacts

{figure_list}

Sweep tables are written to `{cfg['run']['table_dir']}/sensitivity_*.csv`.
"""

    return _write(path, [intro, method, planning])
